### ISSUE TITLE
Fix payout report totals with refunds

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1361]
Payout reports that include refunds should show the gross column with negative amount. Currently it shows the positive amount so the refund is being counted as an additional payment. The correct amount is being paid out which is good but it's confusing for reports.

@jlyon I can review the detail offline for privacy sake.

**Comment by jlyon** [comment]
This has been fixed @kevindherman

**Comment by kevindherman** [comment]
@jlyon the export report CSV still doesn't give a negative value to the refund amount. The fees are reflected accurately in the export report but total column is behaving like it was pre-fix.
