### ISSUE TITLE
Add meeting post type

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1401]
Outstanding todos
- [x] Fix sort and display on teaser widget `wp-content/plugins/wp-proud-core/modules/proud-teasers/proud-teasers.php` line 506
- [x] Go through what displays on teaser
- [x] Go over display of post type
- [x] Responsive (100% width) video @aschmoe
- [ ] How do we get these docs in elastic @aschmoe?
- [ ] There currently is now way to remove a selected document
- [x] Push admin theme fixes for edit form
- [ ] Infinite attachments field
- [ ] Add to citytemplate, other sites that are interested

---
@kevindherman 's list
- [x] Change agenda to "agenda packet"
- [x] Completed meetings should include a "minutes" tab
- [x] Completed meeting page tabs should go in the order of agenda packet, minutes, video, contact info
- [x] Category label should display (this might've been missing because of the widget work)
- [x]  Option to only have download button and not preview PDF would be nice
- [x]  Hide video bookmarks if they don't create bookmarks

**Comment by jlyon** [comment]
@kevindherman I pushed updates as a hotfix to Fairfax, Lucas, and beta.proudcity.com (u: proudcity, p: demo):
- Fixed selection of files on the Meeting edit page
-  Templating display of Meeting page, including tabs, document preview, Youtube bookmark functionality
- Initial attempt on list widgets (still needs work)

**Comment by kevindherman** [comment]
@jlyon thanks for fixing the file upload issue. 

A couple thoughts:
1- Completed meetings should include a "minutes" tab
2- Category tag for meeting type (this might've been missing because of the widget work)
3- I'm going to ask about the video being the default tab, I have a feeling they'll want the agenda first.

**Comment by kevindherman** [comment]
@jlyon awesome. Looking forward to it.

**Comment by jlyon** [comment]
@kevindherman I took care of most of the items on your list and pushed the latest to beta only.  Have a look before our meeting.

- I added the filename to the download button list (it was confusing without it)

>  Hide video bookmarks if they don't create bookmarks
This seemed to already be the case for me: https://beta.proudcity.com/meetings/completed-2/. I think we do need to try to make the video responsive (ie full-width in without bookmarks)

>  Category label should display (this might've been missing because of the widget work)
We should talk about this tomorrow.  It looks like it's actually not displaying on most post types (News, Events).

**Comment by jlyon** [comment]
1- can you add a media field for audio that works with SoundCloud? Like video this tab should only display if they have entered information
2- will the widget have a table view that displays name, agenda, minutes, video, audio?

**Comment by jlyon** [comment]
@kevindherman 
> 1- can you add a media field for audio that works with SoundCloud? Like video this tab should only display if they have entered information

I added this field to the edit page.  It hasn't been added to the front-end yet (will happen in the next release). Do you think it should be its own tab, or should we change Video to Media and add it there?

2- will the widget have a table view that displays name, agenda, minutes, video, audio?

I can a table display to the widget in the next release.

**Comment by jlyon** [comment]
@kevindherman I changed the Meeting list widget so it just displays both upcoming and completed meetings in one list. Upcoming meetings will display Add to Calendar and Get Directions buttons.  Completed meetings will not.

I updated https://fairfax-ca.proudcity.com/meetings/ so that there is a meetings list at the bottom of the page. We can add more filters, etc to this.

**Comment by kevindherman** [comment]
@jlyon a few questions/comments after a quick looks:

1- Will the meeting list widget allow for you to select categories within the edit widget view or do you need to also place a meetings filter widget on that page? I didn't see either option so let me know what you're thinking on that front.
2- I think displaying upcoming and past meetings in one place is the right move. However, I think the table view that shows the supporting tabs as available will what people will use so the sooner the better on that. 
3- Audio: should be it's own tab that is hidden if not used. Totally fine to come at a later release, this is the lowest priority just needed to know we can add it. 

I think item one could be a blocker for Fairfax's launch so that they can put different meetings on different pages (departments, commissions, etc.). The table view is likely preferred but maybe not a blocker if we needed prioritize these ahead of the launch next week.

**Comment by jlyon** [comment]
@kevindherman I finished this up locally, but ran into issues when I tried to deploy it on Fairfax tonight (the whole widget disappeared), so I reverted back to what we had there previously.  

This is what the table view will look like.  Each label takes you to that specific tab on the Meeting detail page.  

This will get into the release this week.

**Comment by kevindherman** [comment]
@jlyon that table looks great. We'll need to bump the launch back a week since they won't get to implement it until Friday morning.

**Comment by kevindherman** [comment]
@jlyon I don't see it in the checklist above, unless it's part of the first item, but the meeting list widget should have the ability to select specific categories to display. Is that part of the updates for the release?

**Comment by jlyon** [comment]
Order in table view is now
- meeting name 
- date
- content available?

Filter by category in the widget is now fixed.

**Comment by jlyon** [comment]
Added the table view, filtered to Town Council to https://fairfax-ca.proudcity.com/meetings/

**Comment by jlyon** [comment]
@kevindherman I just fixed this as Hotfix 1.63.2 and pulled the update on Lucas and Fairfax.

**Comment by kevindherman** [comment]
@jlyon when you select hide date from the meeting list table view it still shows the time:

https://fairfax-ca.proudcity.com/agendas-town-council/
![screenshot 2018-10-29 15 33 59](https://user-images.githubusercontent.com/6032426/47675377-2bb73280-db90-11e8-9106-81e131bf8728.png)
