### ISSUE TITLE
Save agency: Automatically create menu, set WR template

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#15]
- [x] Menu not assigned initially
- [x] Save default WooRockets code
- [x] Automatically create "Police Dept Home" link

**Comment by jlyon** [comment]
@aschmoe ideally, this would default to woorockets enabled in certain instances (`agency_type='section').  let's discuss.

**Comment by aschmoe** [comment]
Fixed this up

**Comment by jlyon** [comment]
@aschmoe didn't seem to work for me. Steps:
1. Create new agency
2. Select Section, add featured image
3. Save
Result: page reloads, but WR is still not enabled

**Comment by jlyon** [comment]
Jeff overwrote on merge commit, to fix

**Comment by jlyon** [comment]
Jeff fixed commit.  One last issue:

Widget titles in left sidebar not showing:
1) Create new section agency, add some social networks, contact, hours info
2) save
3) Default WR template has titles, but no titles appear on the agency sidebar

url: https://example.proudcity.com/agencies/economic-development/. WR template has titles for L sidebar items

**Comment by aschmoe** [comment]
Fixed these up

**Comment by aschmoe** [comment]
@jlyon anything currently necessary here?

**Comment by jlyon** [comment]
yah, the SO code isn't getting set properly.  The code is in there, and it should be working, but it's getting overwritten after I update the metadata i think.

**Comment by jlyon** [comment]
Changes from #210 should get in here (add "Connect" title to social media in L sidebar on agency pages)

**Comment by aschmoe** [comment]
Tag 1.3.1 has the standard template changes

**Comment by aschmoe** [comment]
@jlyon did the section / Site Origin part of this.  Wasn't sure about #210
