### ISSUE TITLE
Petaluma: image card view responsive issues

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#1601]

**Comment by aschmoe** [comment]
@kevindherman this is fixed up, I had to change a little bit how https://petaluma-ca.proudcity.com/city-clerk-committees/ was done... they had multiple image blocks in the columns, I've added an additional row to allow them to be equal.  Other pages that emulate this style will have to do the same

**Comment by jlyon** [comment]
@kevindherman I re-read this issue and saw that there was something with the news boxes. News boxes look good on https://petaluma-ca.proudcity.com/departments/police-department and https://petaluma-ca.proudcity.com/departments/city-clerk/.  If there is still an immediate high pri issue with these, can you send me an example page where the news posts don't look right?

One issue I am seeing is that the non-news posts are extending down if there are two lines of text. Is is this something I should try to fix?
![Screenshot (9)](https://user-images.githubusercontent.com/550909/64494391-0c257780-d241-11e9-815a-47019236fefb.png)

**Comment by kevindherman** [comment]
@jlyon the news cards do appear to be fixed which was one of the primary concerns. 

The image cards with two lines of text resizing is still an issue on a couple of the dept pages. Here are some other examples:

https://petaluma-ca.proudcity.com/departments/city-clerk/
https://petaluma-ca.proudcity.com/departments/public-works/

**Comment by jlyon** [comment]
Ok I will look into that

**Comment by jlyon** [comment]
@kevindherman this is what they want, right (I didn't want to make any changes to this without being 100% sure what we're after):
<img width="1142" alt="Screen Shot 2019-09-08 at 11 00 55 PM" src="https://user-images.githubusercontent.com/550909/64506611-09507400-d28d-11e9-9df9-45907cba3ae2.png">

```
    position: absolute;
    bottom: 0;
    background: #78695d;
    width: 100%;
```

**Comment by kevindherman** [comment]
@jlyon the commissions page is a good example of what they want:
https://petaluma-ca.proudcity.com/city-clerk-committees/

![Screenshot 2019-09-09 09 49 11](https://user-images.githubusercontent.com/6032426/64536456-303b9400-d2e7-11e9-9ecd-438560fb1e8e.png)

**Comment by jlyon** [comment]
@kevindherman The equal heigh requires:
1. Each row to be its own row
2. Under attributes, we need to add the `equalize-column-images` class.

Because these image blocks are not in their own row, we can't set this up like we have set up the other ones.  Our options are:
a) set it up like the screenshot above
b) do (a), but make it so the brown bar has a minimum height to accomodate 2 rows of text. This will probably look decent on desktop, but will not look great on mobile.

I don't think I'll be able to set this up before the meetings today, but I can set up whichever route we decide to go down tonight.

**Comment by kevindherman** [comment]
@jlyon this is good to know and I'll discuss.

It looks like they got rid of a bunch of the problematic language by trying to keep the text to one line as much as possible so it could be less of an issue than before. 

I'll post back when a decision is made.
