### ISSUE TITLE
Show location featured media in map

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#382]
When you manually add locations using the wordpress option the location description  and featured image aren't displaying on the front-end.

https://warr-acres-ok.proudcity.com/economic-development/

![screenshot 2016-05-26 14 18 55](https://cloud.githubusercontent.com/assets/6032426/15585347/d12a7abe-234c-11e6-879e-da4efbea0bcf.png)

![screenshot 2016-05-26 14 17 03](https://cloud.githubusercontent.com/assets/6032426/15585346/d12902d8-234c-11e6-86df-8dbf2a0b863e.png)

**Comment by jlyon** [comment]
Fixed

**Comment by kevindherman** [comment]
@jlyon the information is showing on this but the featured image still isn't making it to the front-end detail.

**Comment by jlyon** [comment]
need to load in `post._links['https://api.w.org/featuredmedia'].href` in http://localhost:8080/wp-json/wp/v2/locations/?direction=ASC&filter%5Blocation-taxonomy%5D=police&sort=date&per_page=100 that will load something like http://localhost:8080/wp-json/wp/v2/media/3008.

**Comment by jlyon** [comment]
I finally set this up while working on #519.  The featured image appears below the title, above the contact info. 

![screenshot from 2016-09-21 15 29 13](https://cloud.githubusercontent.com/assets/550909/18731330/2bf41700-8010-11e6-83a0-3d589209e1ff.png)
