### ISSUE TITLE
Social links on contact page are broken

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#389]
"The social links do not work, and one shows up for Parks which is the one that I deleted and it kept coming back."

 See #388 for parks and rec contact bug.

**Comment by jlyon** [comment]
Fixed the field saving/resetting issues in #388.

>"The social links do not work, and one shows up for Parks which is the one that I deleted and it kept coming back." 

I think this was because the Social links widget wasn't added to the agency landing pages. I added to parks and rec. It seemed like it was added to the other agencies that had social media links added.

Are they trying to setup the social wall too?

**Comment by kevindherman** [comment]
@jlyon the social links widget on the agency is working but the social links on contact still don't work. After clicking the button /contact refreshes

https://warr-acres-ok.proudcity.com/contact/

**Comment by jlyon** [comment]
Fixed this in the release.
