### ISSUE TITLE
Contact display: Fix label for Position field

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#681]
In the staff directory, it says "Social Media" where it should say "Position":
https://san-rafael-ca.proudcity.com/contacts/rebecca-woodbury/

![contact](https://cloud.githubusercontent.com/assets/6032426/20672879/d48e6b84-b550-11e6-8f80-751a8491e5a8.JPG)

Also, looks like the Position is not showing up on all entries:
https://san-rafael-ca.proudcity.com/contacts/cristine-alilovich/

![contact2](https://cloud.githubusercontent.com/assets/6032426/20672915/f323028a-b550-11e6-9e30-14f78d92c389.JPG)

**Comment by jlyon** [comment]
Fixed this.

**Comment by kevindherman** [comment]
@jlyon I cleared my cache and this issue still persists. Can you take another look?
