### ISSUE TITLE
Login/redirect issue

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#723]
Good morning Rebecca and Kevin!
I’m having log on issues this morning. I need to cancel some upcoming PC and DRB meetings on the events. I go to the proud city log on, it works fine and then sends me to the home page (https://www.cityofsanrafael.org/?message=TheredirectURIiswrong.Yousendhttps%3A%2F%2Fwww.cityofsanrafael.org%2Candweexpectedhttps%3A%2F%2Fsan-rafael-ca.proudcity.com#/city/answers) with no icon for editing or the dashboard…is it user error on my end or did something change with the switch? I had Luis try it too to make sure it wasn’t my log on, his computer did the same thing

![unnamed 1](https://cloud.githubusercontent.com/assets/6032426/21056995/d4300c16-be05-11e6-83ec-c8d9a55bf52e.png)

**Comment by jlyon** [comment]
@kevindherman I added a temporary fix.  On my.proudcity.com, there are links below the login box to login to SR or SR Comm Svcs.  Click on those links and then enter your username and password there.

We are working on a long-term fix and should have a much better login experience in place by Monday morning .

**Comment by kevindherman** [comment]
@jlyon still having some trouble:

 I get this page after going to my.proudcity and then logging in and selection san Rafael city:
![image001](https://cloud.githubusercontent.com/assets/6032426/21063173/496b0762-be22-11e6-82e2-f0278055428e.jpg)

**Comment by jlyon** [comment]
@kevindherman Try reloading that page, and the login box should come up again on that page.

if they're still having issues, try a new browser

sorry, we're working on a better fix, but it might take a little longer

**Comment by jlyon** [comment]
@kevindherman I updated and reconfigured Auth0  and this is now fixed.

**Comment by kevindherman** [comment]
@jlyon awesome.

I'll report back if they continue to have issues.

**Comment by kevindherman** [comment]
@jlyon this was working fine but then I was logged out and in logging back in I ran into some issues. 

I can navigate the site and edit pages but if I click on the "dashboard" link in the top right I am redirected to this page: https://cloud.githubusercontent.com/assets/6032426/21063173/496b0762-be22-11e6-82e2-f0278055428e.jpg

If I click on back to San Rafael it logs me out.

**Comment by kevindherman** [comment]
@jlyon this is what Parks is getting from my.proudcity.com

![url mismatch](https://cloud.githubusercontent.com/assets/6032426/21111144/29e32d36-c06e-11e6-9385-1602eaff4383.JPG)

**Comment by kevindherman** [comment]
@jlyon just talked to the Parks and this error comes up after she logins and selects Community Services from her site list. She said that if she selects the main site it navigates to the main site but logs her out.

This sounds similar to what I was experiencing in selecting a the specific site to edit.

**Comment by kevindherman** [comment]
@jlyon  This just came in from PO. The URL with the error message has Auth0 in it so I wonder if it's related:

I am trying to update the City Council Video page. I have tried several times and keep receiving the same error message (attached). I am not sure if this should be for our IT or ProudCity. 
I was able to add a notice this morning with no issue. 

[Doc4.pdf](https://github.com/proudcity/wp-proudcity/files/646852/Doc4.pdf)

**Comment by jlyon** [comment]
@kevindherman I fixed the parks issue.

@kevindherman The issue with the https://www.cityofsanrafael.org/?message=Invalidauthorizationcode#/city/answers in the url should be fixed now as well after you login on https://my.proudcity.com/#https://www.cityofsanrafael.org (note the url change).

**Comment by kevindherman** [comment]
@jlyon this popped up again for Rebecca who was fine all day. Same issue being able to login but clicking dashboard logs her out.

**Comment by jlyon** [comment]
This has happened to me once today. I think it's lingering stuff in her cache from the old setup.  If she goes back to http://www.cityofsanrafael.org/login.php, a little "You previously logged in" box should appear again and it seems have fixed the issue for me @kevindherman .

**Comment by kevindherman** [comment]
@jlyon I've tried everything this morning and I'm still getting the same problem.

**Comment by kevindherman** [comment]
@jlyon steps:

1. restarted chrome browser
2. cleared cache
3. opened incognito window
4. https://my.proudcity.com/#https://www.cityofsanrafael.org
5. logged in using support@ accounts
6. land on homepage with editing bar
![screenshot 2016-12-13 12 49 48](https://cloud.githubusercontent.com/assets/6032426/21152022/a8cca36a-c132-11e6-972b-2312a644971f.png)
7. Can edit by navigating and selecting "edit" 
https://www.cityofsanrafael.org/wp-admin/post.php?post=3186&action=edit
![screenshot 2016-12-13 12 51 08](https://cloud.githubusercontent.com/assets/6032426/21152068/d5952a2a-c132-11e6-8482-47822ded8726.png)
8. If I click dashboard on the top left I am redirected to this page:
https://www.cityofsanrafael.org/wp-login.php?redirect_to=https%3A%2F%2Fwww.cityofsanrafael.org%2Fwp-admin%2F&reauth=1
![screenshot 2016-12-13 12 52 14](https://cloud.githubusercontent.com/assets/6032426/21152102/fd656fba-c132-11e6-989f-11c8836cabe2.png)
9. Click "back to San Rafael" and it took me to the homepage and still logged in.
![screenshot 2016-12-13 12 53 05](https://cloud.githubusercontent.com/assets/6032426/21152174/3e325378-c133-11e6-8521-a313d4894b73.png)
10. Clicked dashboard which logged me out and sent me to this page:
https://proudcity.auth0.com/login?client=Ol3dDZI2hexRLFGclKROKCQ8DzERqcOY&protocol=oauth2&redirect_uri=https%3A%2F%2Fwww.cityofsanrafael.org%2Findex.php%3Fauth0%3D1&scope=openid%20&response_type=code&responseType=code&callbackURL=https%3A%2F%2Fwww.cityofsanrafael.org%2Findex.php%3Fauth0%3D1&socialBigButtons=false&gravatar=true&rememberLastLogin=true&sso=true&icon=https%3A%2F%2Fmy.proudcity.com%2Fimages%2FIconBlack.png&container=auth0-login-form&disableSignupAction=true&callbackOnLocationHash=false&auth0Client=eyJuYW1lIjoibG9jay5qcyIsInZlcnNpb24iOiIxMC4zLjAiLCJsaWJfdmVyc2lvbiI6IjcuMS4wIn0&state=6oY1Kj9gNJUu0tAw3coLyR8HON9kk0_V
![screenshot 2016-12-13 12 55 05](https://cloud.githubusercontent.com/assets/6032426/21152205/6360dc14-c133-11e6-9238-1879fb3bbe2f.png)
11. Tried logging back in using the support@ credentials
12. Sent to the homepage, logged in
13. Click dashboard, sent back to: 
https://www.cityofsanrafael.org/wp-login.php?redirect_to=https%3A%2F%2Fwww.cityofsanrafael.org%2Fwp-admin%2F&reauth=1
![screenshot 2016-12-13 12 56 51](https://cloud.githubusercontent.com/assets/6032426/21152279/a0fa1388-c133-11e6-9bc1-2fc2c664ed95.png)
14. click "back to San Rafael" and the homepage loads slowly and eventually bring the editor bar up. 
15. click dashboard and I am brought back to the screen from step 13.
16. click "back to San Rafael" and it sends me back to the homepage but logged out.
17. In a new tab I go to: https://www.cityofsanrafael.org/login.php which logs me back in
![screenshot 2016-12-13 13 00 48](https://cloud.githubusercontent.com/assets/6032426/21152443/3ac3ad3a-c134-11e6-8ec4-1725bfc7561a.png)
18. click dashboard and brought to:
https://www.cityofsanrafael.org/wp-login.php?redirect_to=https%3A%2F%2Fwww.cityofsanrafael.org%2Fwp-admin%2F&reauth=1
![screenshot 2016-12-13 13 02 13](https://cloud.githubusercontent.com/assets/6032426/21152484/621ba0d6-c134-11e6-97be-7e25fd615524.png)
19. Brought back to the homepage but logged out
![screenshot 2016-12-13 13 03 25](https://cloud.githubusercontent.com/assets/6032426/21152525/8e59a9c2-c134-11e6-9307-2d9c255a693b.png)

**Comment by jlyon** [comment]
Thanks for the notes and screenshots, @kevindherman.  I was able to replicate all of your steps  I fixed the root issue: I changed the URL of the  Dashboard link in the topbar to something that won't log you out. I pushed this platform-wide as a hotfix.

 I'm going to play around  with some of the weird redirect loops in the backend login pages later this afternoon, but the customer-facing issues should be fixed now.

**Comment by kevindherman** [comment]
@jlyon this worked for the majority of the people. I'm almost certain that the people who are still unable to login are all using the login with google feature.

I just watched one of them go through the following steps:

1- my.proudcity.com
2- enter email Christine.Foster@cityofsanrafael.org and password 
3- select login with google
4- this page comes up: https://www.cityofsanrafael.org/index.php?auth0=1&code=0RiJIZA2dti42GTF
![pastedimage 3](https://cloud.githubusercontent.com/assets/6032426/21160680/b6add104-c153-11e6-858a-a1d5f1f2cb0d.png)

Is there anything else that would help diagnose this?

**Comment by jlyon** [comment]
@kevindherman I think her issue was that she had logged in with a password, and then logged in the next time with Google.  I just set it so that accounts are matched based on email address.  This should be fixed.
