### ISSUE TITLE
Some media list view dept's showing as ovals

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#927]
https://danvers-ma.proudcity.com/government/

![screenshot 2017-03-21 22 41 08](https://cloud.githubusercontent.com/assets/6032426/24179859/240c8b74-0e88-11e7-8ecf-4f87db183af6.png)

**Comment by kevindherman** [comment]
Maybe something to do with departments starting with the letter F?

**Comment by jlyon** [comment]
@aschmoe can you look at this one?

**Comment by kevindherman** [comment]
@aschmoe @jlyon can this be resolved ahead of the launch Thursday afternoon?

**Comment by jlyon** [comment]
@kevindherman yes

**Comment by aschmoe** [comment]
Yes I pushed up fixes for this last week.

**Comment by kevindherman** [comment]
@aschmoe @jlyon I'm still getting the ovals after clearing my cache in all my browsers, including private/incognito. Can you double check to make sure it was pushed before the launch?
